// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnkydnueuspmxjiuzbvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRua3lkbnVldXNwbXhqaXV6YnZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0NjcyMzMsImV4cCI6MjA1MzA0MzIzM30.dSWJ6Sxu3wqJWuT43jRVGmq8qbRAIAbCe9Qt0bDPGcs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);